const posts = [{title: "【香川女子旅】<br>「ご当地グルメ&小豆島の旅」",
                number: "［旅記録 #1］",
                category: "国内",
                area: "香川",
                year: 2025,
                month: 8,
                date: "2025.08.23〜24",
                description: "1泊2日で親友と香川へ<br>ご当地グルメを楽しみ、小豆島にも訪れました",
                image: "images/kagawa-1.jpg",
                url: "travel-1.html"},
               {title: "【長野一人旅 Day1】<br>「善光寺に栗の町\"小布施\"を巡る」",
                number: "［旅記録 #2］",
                category: "国内",
                area: "長野",
                year: 2025,
                month: 9,
                date: "2025.09.18〜19",
                description: "前日に急遽思い立ち、長野へ一人旅へ。<br>素敵な出会いが沢山の旅です。",
                image: "images/nagano-19.jpg",
                url: "travel-2.html"},
               {title: "【長野一人旅 Day2】<br>「志賀高原と花々とお猿たち」",
                number: "［旅記録 #3］",
                category: "国内",
                area: "長野",
                year: 2025,
                month: 9,
                date: "2025.09.18〜19",
                description: "前日に急遽思い立ち、長野へ一人旅へ。<br>素敵な出会いが沢山の旅です。",
                image: "images/nagano-40.jpg",
                url: "travel-3.html"},
               {title: "【台湾女子旅 Day1】<br>「台北到着！ドタバタ旅行の幕開け」",
                number: "［旅記録 #4］",
                category: "海外",
                area: "台湾",
                year: 2025,
                month: 9,
                date: "2025.09.28〜30",
                description: "大学の友達と台湾へ！<br>ドタバタで最高に楽しかった旅の記録です。",
                image: "images/taiwann-10.jpg",
                url: "travel-4.html"}];