const posts = [{title: "【香川女子旅】<br>「ご当地グルメ&小豆島の旅」",
                number: "［旅記録 #1］",
                category: "国内",
                area: "香川",
                year: 2025,
                month: 8,
                date: "2025.08.23〜24",
                description: "1泊2日で親友と香川へ<br>ご当地グルメを楽しみ、小豆島にも訪れました",
                image: "images/kagawa-1.jpg",
                url: "travel-1.html"},
               {title: "【長野一人旅 Day1】<br>「善光寺に栗の町\"小布施\"を巡る」",
                number: "［旅記録 #2］",
                category: "国内",
                area: "長野",
                year: 2025,
                month: 9,
                date: "2025.09.18〜19",
                description: "前日に急遽思い立ち、長野へ一人旅へ。<br>素敵な出会いが沢山の旅です。",
                image: "images/nagano-19.jpg",
                url: "travel-2.html"},
               {title: "【長野一人旅 Day2】<br>「志賀高原と花々とお猿たち」",
                number: "［旅記録 #3］",
                category: "国内",
                area: "長野",
                year: 2025,
                month: 9,
                date: "2025.09.18〜19",
                description: "前日に急遽思い立ち、長野へ一人旅へ。<br>素敵な出会いが沢山の旅です。",
                image: "images/nagano-40.jpg",
                url: "travel-3.html"},
               {title: "【台湾女子旅 Day1】<br>「台北到着！ドタバタ旅行の幕開け」",
                number: "［旅記録 #4］",
                category: "海外",
                area: "台湾",
                year: 2025,
                month: 9,
                date: "2025.09.26〜28",
                description: "大学の友達と台湾へ！<br>ドタバタで最高に楽しかった旅の記録です。",
                image: "images/taiwann-10.jpg",
                url: "travel-4.html"},
               {title: "【台湾女子旅 Day2】<br>「リアル千と千尋の町九份と士林夜市で屋台飯」",
                number: "［旅記録 #5］",
                category: "海外",
                area: "台湾",
                year: 2025,
                month: 9,
                date: "2025.09.26〜28",
                description: "大学の友達と台湾へ！<br>ドタバタで最高に楽しかった旅の記録です。",
                image: "images/taiwann-11.jpg",
                url: "travel-5.html"},
               {title: "【台湾女子旅 Day3】<br>「台北で朝ご飯、そして帰国」",
                number: "［旅記録 #6］",
                category: "海外",
                area: "台湾",
                year: 2025,
                month: 9,
                date: "2025.09.26〜28",
                description: "大学の友達と台湾へ！<br>ドタバタで最高に楽しかった旅の記録です。",
                image: "images/taiwann-34.jpg",
                url: "travel-6.html"},
               {title: "【川越日帰り旅行】<br>「小江戸川越で食べ歩き！」",
                number: "［旅記録 #7］",
                category: "国内",
                area: "埼玉",
                year: 2025,
                month: 9,
                date: "2025.09.29",
                description: "親友と日帰りでふらっと川越散策！<br>氷川神社に美味しいグルメを満喫した日の記録です！",
                image: "images/kawagoe-1.jpg",
                url: "travel-7.html"},
               {title: "【滋賀女子旅 Day1】<br>「名古屋に寄り道して滋賀へ！」",
                number: "［旅記録 #8］",
                category: "国内",
                area: "滋賀",
                year: 2026,
                month: 2,
                date: "2026.02.07〜09",
                description: "大学の友達と滋賀旅行<br>日本を寒波が襲う中での旅記録です。",
                image: "images/shiga-1.jpg",
                url: "travel-8.html"},
               {title: "【滋賀女子旅 Day2】<br>「黒壁スクエアにラコリーナから長命寺温泉まで！滋賀を楽しみ尽くす二日目」",
                number: "［旅記録 #9］",
                category: "国内",
                area: "滋賀",
                year: 2025,
                month: 9,
                date: "2025.09.29",
                description: "大学の友達と滋賀旅行<br>日本を寒波が襲う中での旅記録です。",
                image: "images/shiga-1.jpg",
                url: "travel-9.html"},];